- hosts: dockerservers
  become: yes

  tasks:
  - name: install tools
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      pkg:
      - net-tools
      - nfs-client

- hosts: raspis
  become: yes

  tasks:
  - name: install tools
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
      pkg:
      - net-tools
      - raspberrypi-kernel-headers
      - wireguard
      - wireguard-tools
      - iptables