- hosts: opnsense
  connection: local
  gather_facts: no
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: "{{ ansible_host }}"
      api_credential_file: '/home/nilsblume/ansible/.opnsense-test.key'
      ssl_verify: false

  tasks:
    - name: pull updates
      ansibleguy.opnsense.system:
        action: 'update'

    - name: start upgrade, may take long - will wait until finished (timeout 900s)
      ansibleguy.opnsense.system:
        action: 'upgrade'
        timeout: 900

    - name: run audit
      ansibleguy.opnsense.system:
        action: 'audit'

