- hosts: dockerservers
  gather_facts: yes

  tasks:
  - name: create docker reverseproxy network
    community.docker.docker_network:
      name: reverseproxy
      state: present

  - name: portainer
    community.docker.docker_container:
      name: portainer
      image: portainer/portainer-ee:latest
      state: started
      # recreate: true
      ports:
        - "9000:9000"
      restart_policy: "unless-stopped"
      mounts:
        - source: "/var/run/docker.sock"
          target: "/var/run/docker.sock"
          type: "bind"
          consistency: "default"
        - source: "/var/lib/docker/volumes"
          target: "/var/lib/docker/volumes"
          type: "bind"
        - source: "portainer_data"
          target: "/data"
          type: "volume"
      networks:
        - name: "reverseproxy"
      labels:
        traefik.enable: "true"
      # Frontend
        traefik.http.routers.portainer.rule: "Host(`docker.home.nilsblume.de`)"
        traefik.http.routers.portainer.tls: "true"
        # traefik.http.routers.portainer.tls.certresolver: "le"
        traefik.http.services.portainer.loadbalancer.server.port: "9000"
        traefik.http.routers.portainer.service: "portainer"
